version: '3.7'

services:

  # Tu servicio de Vue.js (Frontend)
  vue:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - VUE_APP_API_URL=http://48.217.185.80/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run serve
  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: recipesSpain
      MYSQL_USER: root
      #MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql  
    ports:
      - "3306:3306"  

  # Servicio phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 1234 
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: db  
    ports:
      - "8081:80"  
    depends_on:
      - db  
  # Tu servicio de Flask (Backend)
  flask:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DB=recipesSpain
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db   
volumes:
  mysql-data:
