services:
  flask:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "8080:80"
    depends_on:
      - flask 
