services:
  # 1. Base de datos MySQL (Render no ofrece MySQL gestionado, usaremos un contenedor)
  - type: web
    name: mysql-db
    runtime: docker
    dockerfilePath: Dockerfile.mysql  # Necesitarás crear este archivo
    env:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: recipesSpain
      MYSQL_USER: root
    plan: shared  # MySQL no puede ir en plan "free" (requiere contenedor persistente)

  # 2. Backend Flask (Python)
  - type: web
    name: flask-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    env:
      MYSQL_HOST: mysql-db  # Nombre del servicio MySQL
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: recipesSpain
      FLASK_ENV: production
    plan: free

  # 3. Frontend Vue (Static Site)
  - type: web
    name: vue-frontend
    runtime: node
    buildCommand: |
      cd frontend && npm install && npm run build
    staticSite: true
    publish: frontend/dist
    env:
      VUE_APP_API_URL: https://flask-backend.onrender.com  # Cambia a tu URL de Flask en Render
    routes:
      - path: /*
        staticSite: true  # Para Vue Router
    plan: free