# render.yaml

services:
  # 1. Base de datos PostgreSQL
  - type: postgres
    name: mi-db-flask
    plan: free  # Cambia a "starter" o "standard" en producción
    databaseName: flask_db
    user: flask_user

  # 2. Backend con Flask (Python)
  - type: web
    name: backend-flask
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app  # Ajusta "app:app" según tu archivo Flask
    env:
      DATABASE_URL: postgres://flask_user:@mi-db-flask:5432/flask_db
      FLASK_ENV: production
      # Otras variables que necesites (ej: SECRET_KEY)
    plan: free

  # 3. Frontend con Vue (Static Site)
  - type: web
    name: frontend-vue
    runtime: node
    buildCommand: |
      cd frontend && npm install && npm run build
    staticSite: true  # Importante para Vue/React
    publish: frontend/dist  # Ruta donde se genera el build
    env:
      VITE_API_URL: https://backend-flask.onrender.com  # Usado en axios/fetch
    plan: free