# Backend - Flask API
- type: web
  name: flask-backend
  env: docker
  buildCommand: docker build -t flask-backend .  # Construir imagen Docker de Flask
  startCommand: docker run -p 5000:5000 flask-backend  # Ejecutar contenedor Flask
  envVars:
    - key: MYSQL_HOST
      value: mysql-db  # Nombre del servicio de MySQL en Render
    - key: MYSQL_USER
      value: root
    - key: MYSQL_PASSWORD
      value: 1234
    - key: MYSQL_DB
      value: recipesSpain
  routes:
    - source: /api/*
      destination: http://localhost:5000/api/*  # Redirigir las rutas /api a Flask

# Frontend - Vue.js (Static Site)
- type: web
  name: vue-frontend
  env: static
  rootDir: frontend  # Directorio donde está tu frontend (con Dockerfile)
  buildCommand: npm install && npm run build  # Instalar dependencias y construir la app Vue
  staticPublishPath: dist  # Directorio generado por `npm run build` que contiene los archivos estáticos
  envVars:
    - key: VUE_APP_API_URL
      value: https://saboresespa-a-1.onrender.com  # URL de tu backend de Flask
  routes:
    - source: /*  # Redirigir todas las rutas de frontend
      destination: /index.html  # Redirigir todo a index.html para las rutas SPA

# MySQL Database - Managed MySQL Database on Render
- type: database
  name: mysql-db
  engine: mysql
  version: 8.0
  plan: free  # O ajusta el plan según sea necesario
  envVars:
    - key: MYSQL_ROOT_PASSWORD
      value: 1234  # Contraseña root para la base de datos
    - key: MYSQL_USER
      value: root  # Usuario root para MySQL
    - key: MYSQL_PASSWORD
      value: 1234  # Contraseña para el usuario root
    - key: MYSQL_DB
      value: recipesSpain  # Nombre de la base de datos
