export const ingredientes = {
  // Condimentos y básicos
  "Aceite de oliva": "Aceite, vinagre y sal",
  "Aceite de oliva virgen extra": "Aceite, vinagre y sal",
  "Aceite de girasol": "Aceite, vinagre y sal",
  "Vinagre de vino": "Aceite, vinagre y sal",
  "Vinagre de manzana": "Aceite, vinagre y sal",
  "Viangre de Jerez":"Aceite, vinagre y sal",
  "Sal": "Aceite, vinagre y sal",
  "Sal gruesa": "Aceite, vinagre y sal",
  "Pimienta negra": "Especias",
  "Pimentón dulce": "Especias",
  "Pimentón picante": "Especias",
  "Orégano": "Especias",
  "Tomillo": "Especias",
  "Romero": "Especias",
  "Laurel": "Especias",
  "Curry": "Especias",
  "Nuez moscada": "Especias",
  "Clavo": "Especias",
  "Comino": "Especias",
  "Azafrán":"Especias",

  // Salsas
  "Mayonesa": "Mayonesa, ketchup y mostaza",
  "Mostaza": "Mayonesa, ketchup y mostaza",
  "Ketchup": "Mayonesa, ketchup y mostaza",
  "Salsa barbacoa": "Otras salsas",
  "Salsa de soja": "Otras salsas",
  "Salsa alioli": "Otras salsas",

  // Conservas y tomate
  "Tomate frito": "Tomate",
  "Tomate triturado": "Tomate",
  "Salsa de tomate": "Tomate",
  "Atún en conserva": "Atún y otras conservas de pescado",
  "Sardinas en conserva": "Atún y otras conservas de pescado",
  "Mejillones en escabeche": "Berberechos y mejillones",
  "Berberechos en lata": "Berberechos y mejillones",

  // Carnes
  "Pollo": "Aves y pollo",
  "Pechuga de pollo": "Aves y pollo",
  "Muslos de pollo": "Aves y pollo",
  "Carne picada de cerdo": "Cerdo",
  "Costillas de cerdo": "Cerdo",
  "Filete de ternera": "Vacuno",
  "Carne picada de ternera": "Vacuno",
  "Conejo": "Conejo y cordero",
  "Cordero": "Conejo y cordero",

  // Embutidos
  "Chorizo": "Embutido curado",
  "Morcilla": "Embutido curado",
  "Salchichón": "Embutido curado",
  "Jamón serrano": "Jamón serrano",
  "Jamón cocido": "Aves y jamón cocido",
  "Jamón": "Aves y jamón cocido",
  "Jamón ibérico": "Aves y jamón cocido",
  "Lomo embuchado": "Embutido curado",
  "Sobrasada": "Paté y sobrasada",
  "Salchichas frankfurt": "Bacón y salchichas",

  // Pescados y mariscos
  "Bacalao desalado": "Pescado",
  "Merluza": "Pescado",
  "Salmón": "Pescado",
  "Gambas": "Marisco",
  "Langostinos": "Marisco",
  "Pulpo": "Marisco",
  "Calamares": "Marisco",

  // Lácteos y huevos
  "Leche": "Leche y bebidas vegetales",
  "Leche entera": "Leche y bebidas vegetales",
  "Leche semidesnatada": "Leche y bebidas vegetales",
  "Bebida de avena": "Leche y bebidas vegetales",
  "Mantequilla": "Mantequilla y margarina",
  "Margarina": "Mantequilla y margarina",
  "Queso curado": "Queso curado, semicurado y tierno",
  "Queso fresco": "Queso untable y fresco",
  "Yogur natural": "Yogures naturales y sabores",
  "Huevos": "Huevos",

  // Verduras
  "Patata":"Verdura",
  "Pepino":"Verdura",
  "Patatas medianas":"Verduras",
  "Cebolla": "Verdura",
  "Ajo": "Verdura",
  "Zanahoria": "Verdura",
  "Pimiento rojo": "Verdura",
  "Pimiento verde": "Verdura",
  "Calabacín": "Verdura",
  "Berenjena": "Verdura",
  "Espinacas": "Verdura",
  "Acelgas": "Verdura",
  "Champiñones": "Verdura",
  "Judías verdes": "Verdura",
  "Tomate natural": "Tomate",
  "Tomates": "Verdura",
  "Judía verde":"Verdura",

  // Frutas y frutos secos
  "Manzana": "Fruta",
  "Plátano": "Fruta",
  "Naranja": "Naranja",
  "Piña": "Melocotón y piña",
  "Melocotón": "Melocotón y piña",
  "Pera": "Fruta",
  "Pasas": "Frutos secos y fruta desecada",
  "Higos secos": "Frutos secos y fruta desecada",
  "Almendras": "Frutos secos y fruta desecada",
  "Nueces": "Frutos secos y fruta desecada",

  // Legumbres y cereales
  "Arroz": "Arroz",
  "Arroz bomba": "Arroz",
  "Garbanzos": "Legumbres",
  "Lentejas": "Legumbres",
  "Alubias blancas": "Legumbres",
  "Pasta": "Pasta y fideos",
  "Macarrones": "Pasta y fideos",
  "Espaguetis": "Pasta y fideos",
  "Pan rallado": "Harina y preparado repostería",
  "Pan de barra": "Pan de horno",
  "Pan de molde": "Pan de molde y otras especialidades",
  "Harina": "Harina y preparado repostería",
  "Harina de trigo": "Harina y preparado repostería",
  "Levadura en polvo": "Harina y preparado repostería",

  // Dulces
  "Azúcar": "Azúcar y edulcorante",
  "Miel": "Mermelada y miel",
  "Canela": "Especias",
  "Chocolate negro": "Chocolate",
  "Chocolate con leche": "Chocolate",
  "Cacao en polvo": "Cacao soluble y chocolate a la taza",

  //Caldos
  "Caldo de pollo": "Caldo y puré",
  "Caldo de ave":"Caldo y puré",
  "Caldo de carne": "Caldo y puré",
  "Caldo de pescado": "Caldo y puré",
  "Caldo de verduras": "Caldo y puré",
  "Caldo para paella de pescado y marisco": "Caldo y puré",
  "Fumet de marisco": "Caldo y puré",
  "Fumet de pescado": "Caldo y puré",
  "Caldo casero de cocido": "Caldo y puré",
  "Caldo casero de pollo": "Caldo y puré",
  "Caldo casero de verduras": "Caldo y puré"
};
