export const ingredientes = {
  // Aceites, vinagres y sal
  "Aceite de oliva": "Aceite, vinagre y sal",
  "Aceite de oliva virgen extra": "Aceite, vinagre y sal",
  "Aceite de girasol": "Aceite, vinagre y sal",
  "Aceite de coco": "Aceite, vinagre y sal",
  "Vinagre de vino": "Aceite, vinagre y sal",
  "Vinagre de manzana": "Aceite, vinagre y sal",
  "Vinagre balsámico": "Aceite, vinagre y sal",
  "Vinagre de Jerez": "Aceite, vinagre y sal",
  "Vinagre de Módena": "Aceite, vinagre y sal",
  "Sal": "Aceite, vinagre y sal",
  "Sal gruesa": "Aceite, vinagre y sal",
  "Sal marina": "Aceite, vinagre y sal",
  "Sal yodada": "Aceite, vinagre y sal",
  "Flor de sal": "Aceite, vinagre y sal",

  // Especias
  "Pimienta": "Especias",
  "Pimienta negra": "Especias",
  "Pimienta blanca": "Especias",
  "Pimentón dulce": "Especias",
  "Pimentón picante": "Especias",
  "Orégano": "Especias",
  "Tomillo": "Especias",
  "Romero": "Especias",
  "Laurel": "Especias",
  "Curry": "Especias",
  "Nuez moscada": "Especias",
  "Clavo": "Especias",
  "Comino": "Especias",
  "Azafrán": "Especias",
  "Canela": "Especias",
  "Canela en polvo":"Especias",
  "Canela molida": "Especias",
  "Cardamomo": "Especias",
  "Cúrcuma": "Especias",
  "Jengibre molido": "Especias",
  "Hierbas provenzales": "Especias",
  "Perejil": "Especias",
  "Cilantro": "Especias",
  "Albahaca": "Especias",
  "Mezcla de especias para paella": "Especias",

  // Mayonesa, ketchup y mostaza
  "Mayonesa": "Mayonesa, ketchup y mostaza",
  "Mostaza": "Mayonesa, ketchup y mostaza",
  "Mostaza Dijon": "Mayonesa, ketchup y mostaza",
  "Ketchup": "Mayonesa, ketchup y mostaza",
  "Mayonesa light": "Mayonesa, ketchup y mostaza",

  // Otras salsas
  "Salsa barbacoa": "Otras salsas",
  "Salsa de soja": "Otras salsas",
  "Salsa alioli": "Otras salsas",
  "Salsa tártara": "Otras salsas",
  "Salsa rosa": "Otras salsas",
  "Salsa teriyaki": "Otras salsas",
  "Salsa picante": "Otras salsas",
  "Salsa carbonara": "Otras salsas",
  "Salsa boloñesa": "Otras salsas",
  "Salsa pesto": "Otras salsas",
  "Salsa de ostras": "Otras salsas",
  "Salsa holandesa": "Otras salsas",
  "Salsa bechamel": "Otras salsas",

  // Tomate
  "Tomate frito": "Tomate",
  "Tomate": "Tomate",
  "Tomate triturado": "Tomate",
  "Salsa de tomate": "Tomate",
  "Tomate natural": "Tomate",
  "Tomate cherry": "Tomate",
  "Tomate pera": "Tomate",
  "Tomate en conserva": "Tomate",
  "Tomate seco": "Tomate",
  "Tomate concentrado": "Tomate",

  // Atún y otras conservas de pescado
  "Atún en conserva": "Atún y otras conservas de pescado",
  "Atún en aceite de oliva": "Atún y otras conservas de pescado",
  "Atún al natural": "Atún y otras conservas de pescado",
  "Bonito del norte": "Atún y otras conservas de pescado",
  "Caballa en conserva": "Atún y otras conservas de pescado",
  "Sardinas en conserva": "Atún y otras conservas de pescado",
  "Anchoas": "Atún y otras conservas de pescado",
  "Ventresca de atún": "Atún y otras conservas de pescado",
  "Melva": "Atún y otras conservas de pescado",

  // Berberechos y mejillones
  "Mejillones en escabeche": "Berberechos y mejillones",
  "Mejillones al natural": "Berberechos y mejillones",
  "Berberechos en lata": "Berberechos y mejillones",
  "Mejillones en salsa de tomate": "Berberechos y mejillones",
  "Mejillones en salsa picante": "Berberechos y mejillones",

  // Aves y pollo
  "Pollo": "Aves y pollo",
  "Pechuga de pollo": "Aves y pollo",
  "Muslos de pollo": "Aves y pollo",
  "Alitas de pollo": "Aves y pollo",
  "Pollo troceado": "Aves y pollo",
  "Pavo": "Aves y pollo",
  "Pechuga de pavo": "Aves y pollo",
  "Codorniz": "Aves y pollo",
  "Pato": "Aves y pollo",

  // Cerdo
  "Carne picada de cerdo": "Cerdo",
  "Carne picada": "Hamburguesas y picadas",
  "Costillas de cerdo": "Cerdo",
  "Lomo de cerdo": "Cerdo",
  "Solomillo de cerdo": "Cerdo",
  "Chuletas de cerdo": "Cerdo",
  "Panceta": "Cerdo",
  "Codillo de cerdo": "Cerdo",
  "Secreto ibérico": "Cerdo",
  "Pluma ibérica": "Cerdo",
  "Presunto ibérico": "Cerdo",

  // Vacuno
  "Filete de ternera": "Vacuno",
  "Carne picada de ternera": "Vacuno",
  "Entrecot": "Vacuno",
  "Solomillo": "Vacuno",
  "Chuletón": "Vacuno",
  "Falda": "Vacuno",
  "Redondo": "Vacuno",
  "Buey": "Vacuno",
  "Vaca vieja": "Vacuno",
  "Ternera blanca": "Vacuno",

  // Conejo y cordero
  "Conejo": "Conejo y cordero",
  "Cordero": "Conejo y cordero",
  "Paletilla de cordero": "Conejo y cordero",
  "Chuletas de cordero": "Conejo y cordero",
  "Pierna de cordero": "Conejo y cordero",

  // Embutido curado
  "Chorizo": "Embutido curado",
  "Chorizo ibérico": "Embutido curado",
  "Morcilla": "Embutido curado",
  "Salchichón": "Embutido curado",
  "Salchichón ibérico": "Embutido curado",
  "Lomo embuchado": "Embutido curado",
  "Fuet": "Embutido curado",
  "Longaniza": "Embutido curado",
  "Cecina": "Embutido curado",
  "Salchichas de pavo": "Embutido curado",

  // Jamón serrano
  "Jamón serrano": "Jamón serrano",
  "Jamón ibérico": "Jamón serrano",
  "Jamón de bellota": "Jamón serrano",
  "Jamón de cebo": "Jamón serrano",
  "Paleta ibérica": "Jamón serrano",
  "Jamón de Teruel": "Jamón serrano",
  "Jamón de Jabugo": "Jamón serrano",

  // Aves y jamón cocido
  "Jamón cocido": "Aves y jamón cocido",
  "Jamón york": "Aves y jamón cocido",
  "Jamón de pavo": "Aves y jamón cocido",
  "Pechugas de pavo": "Aves y jamón cocido",
  "Pechuga de pollo cocida": "Aves y jamón cocido",

  // Paté y sobrasada
  "Sobrasada": "Paté y sobrasada",
  "Paté": "Paté y sobrasada",
  "Paté de cerdo": "Paté y sobrasada",
  "Paté de olivas": "Paté y sobrasada",
  "Paté de atún": "Paté y sobrasada",
  "Paté de hígado": "Paté y sobrasada",
  "Foie gras": "Paté y sobrasada",

  // Bacón y salchichas
  "Bacon": "Bacón y salchichas",
  "Bacon ahumado": "Bacón y salchichas",
  "Salchichas frankfurt": "Bacón y salchichas",
  "Salchichas frescas": "Bacón y salchichas",
  "Salchichas de pollo": "Bacón y salchichas",
  "Salchichas de pavos": "Bacón y salchichas",
  "Salchichas de cerdo": "Bacón y salchichas",
  "Salchichas tipo alemanas": "Bacón y salchichas",
  "Salchichas cocktail": "Bacón y salchichas",

  // Pescado
  "Bacalao": "Pescado",
  "Bacalao desalado": "Pescado",
  "Merluza": "Pescado",
  "Lubina": "Pescado",
  "Dorada": "Pescado",
  "Salmón": "Pescado",
  "Trucha": "Pescado",
  "Pescadilla": "Pescado",
  "Gallo": "Pescado",
  "Rodaballo": "Pescado",
  "Rape": "Pescado",
  "Corvina": "Pescado",
  "Caballa": "Pescado",
  "Sardinas": "Pescado",
  "Boquerones": "Pescado",
  "Anchoa": "Pescado",
  "Pulpo": "Pescado",
  "Pulpo entero": "Pescado",
  "Sepia": "Pescado",
  "Calamar": "Pescado",

  // Marisco
  "Gambas": "Marisco",
  "Langostinos": "Marisco",
  "Cigalas": "Marisco",
  "Bogavante": "Marisco",
  "Langosta": "Marisco",
  "Nécoras": "Marisco",
  "Buey de mar": "Marisco",
  "Centollo": "Marisco",
  "Percebes": "Marisco",
  "Mejillones": "Marisco",
  "Almejas": "Marisco",
  "Berberechos": "Marisco",
  "Navajas": "Marisco",
  "Vieiras": "Marisco",
  "Zamburiñas": "Marisco",
  "Cangrejo": "Marisco",
  "Calamares": "Marisco",

  // Leche y bebidas vegetales
  "Leche": "Leche y bebidas vegetales",
  "Leche entera": "Leche y bebidas vegetales",
  "Leche semidesnatada": "Leche y bebidas vegetales",
  "Leche desnatada": "Leche y bebidas vegetales",
  "Leche sin lactosa": "Leche y bebidas vegetales",
  "Leche condensada": "Leche y bebidas vegetales",
  "Leche evaporada": "Leche y bebidas vegetales",
  "Bebida de avena": "Leche y bebidas vegetales",
  "Bebida de soja": "Leche y bebidas vegetales",
  "Bebida de almendras": "Leche y bebidas vegetales",
  "Bebida de arroz": "Leche y bebidas vegetales",
  "Bebida de coco": "Leche y bebidas vegetales",

  // Mantequilla y margarina
  "Mantequilla": "Mantequilla y margarina",
  "Mantequilla con sal": "Mantequilla y margarina",
  "Mantequilla sin sal": "Mantequilla y margarina",
  "Margarina": "Mantequilla y margarina",
  "Margarina vegetal": "Mantequilla y margarina",

  // Queso curado, semicurado y tierno
  "Queso manchego": "Queso curado, semicurado y tierno",
  "Queso curado": "Queso curado, semicurado y tierno",
  "Queso semicurado": "Queso curado, semicurado y tierno",
  "Queso tierno": "Queso curado, semicurado y tierno",
  "Queso gouda": "Queso curado, semicurado y tierno",
  "Queso edam": "Queso curado, semicurado y tierno",
  "Queso emmental": "Queso curado, semicurado y tierno",
  "Queso gruyère": "Queso curado, semicurado y tierno",
  "Queso parmesano": "Queso curado, semicurado y tierno",
  "Queso de cabra": "Queso curado, semicurado y tierno",
  "Queso de oveja": "Queso curado, semicurado y tierno",
  "Queso azul": "Queso curado, semicurado y tierno",
  "Queso roquefort": "Queso curado, semicurado y tierno",
  "Queso brie": "Queso curado, semicurado y tierno",
  "Queso camembert": "Queso curado, semicurado y tierno",

  // Queso untable y fresco
  "Queso fresco": "Queso untable y fresco",
  "Queso crema": "Queso untable y fresco",
  "Queso philadelphia": "Queso untable y fresco",
  "Queso de untar": "Queso untable y fresco",
  "Queso de burgos": "Queso untable y fresco",
  "Requesón": "Queso untable y fresco",
  "Ricotta": "Queso untable y fresco",
  "Mozzarella": "Queso untable y fresco",
  "Queso feta": "Queso untable y fresco",

  // Yogures naturales y sabores
  "Yogur natural": "Yogures naturales y sabores",
  "Yogur natural azucarado": "Yogures naturales y sabores",
  "Yogur griego": "Yogures naturales y sabores",
  "Yogur de sabores": "Yogures naturales y sabores",
  "Yogur de fresa": "Yogures naturales y sabores",
  "Yogur de limón": "Yogures naturales y sabores",
  "Yogur de vainilla": "Yogures naturales y sabores",
  "Yogur de frutas": "Yogures naturales y sabores",
  "Yogur desnatado": "Yogures naturales y sabores",
  "Yogur bebible": "Yogures naturales y sabores",
  "Yogur con cereales": "Yogures naturales y sabores",
  "Yogur con miel": "Yogures naturales y sabores",

  // Huevos
  "Huevos": "Huevos",
  "Huevos de gallina": "Huevos",
  "Huevos camperos": "Huevos",
  "Huevos ecológicos": "Huevos",
  "Huevos XL": "Huevos",
  "Huevos L": "Huevos",
  "Huevos M": "Huevos",
  "Huevos S": "Huevos",
  "Claras de huevo": "Huevos",
  "Yemas de huevo": "Huevos",

  // Verdura
  "Patata": "Verdura",
  "Patatas": ["Verdura", "Fruta y verdura", "Patatas", "Tubérculos"],
  "Patatas medianas": ["Verdura", "Patatas"],
  "Cebolla": "Verdura",
  "Ajo": "Verdura",
  "Zanahoria": "Verdura",
  "Pimiento rojo": "Verdura",
  "Pimientos rojos grandes": "Verdura",
  "Pimiento verde": "Verdura",
  "Pimiento amarillo": "Verdura",
  "Pimiento naranja": "Verdura",
  "Calabacín": "Verdura",
  "Berenjena": "Verdura",
  "Calabaza": "Verdura",
  "Espinacas": "Verdura",
  "Acelgas": "Verdura",
  "Coliflor": "Verdura",
  "Brócoli": "Verdura",
  "Col": "Verdura",
  "Col lombarda": "Verdura",
  "Repollo": "Verdura",
  "Lechuga": "Verdura",
  "Escarola": "Verdura",
  "Endibia": "Verdura",
  "Canónigos": "Verdura",
  "Rúcula": "Verdura",
  "Apio": "Verdura",
  "Puerro": "Verdura",
  "Espárragos": "Verdura",
  "Alcachofas": "Verdura",
  "Remolacha": "Verdura",
  "Nabo": "Verdura",
  "Rábano": "Verdura",
  "Chirivía": "Verdura",
  "Pepino": "Verdura",
  "Judías verdes": "Verdura",
  "Guisantes": "Verdura",
  "Habas": "Verdura",
  "Maíz dulce": "Verdura",
  "Tomates": "Verdura",
  "Tomates cherry": "Verdura",
  "Tomate peras": "Verdura",
  "Tomate raf": "Verdura",
  "Tomate kumato": "Verdura",
  "Champiñones": "Verdura",
  "Setas": "Verdura",
  "Boletus": "Verdura",
  "Níscalos": "Verdura",
  "Puerros": "Verdura",
  "Cebolleta": "Verdura",
  "Perejil fresco": "Verdura",
  "Cilantro fresco": "Verdura",
  "Albahaca fresca": "Verdura",
  "Menta fresca": "Verdura",
  "Hierbabuena": "Verdura",
  "Eneldo": "Verdura",
  "Cebollino": "Verdura",
  "Hinojo": "Verdura",
  "Jengibre fresco": "Verdura",
  "Boniato": "Verdura",
  "Batata": "Verdura",

  // Fruta
  "Manzana": "Fruta",
  "Plátano": "Fruta",
  "Pera": "Fruta",
  "Melocotón": "Melocotón y piña",
  "Nectarina": "Melocotón y piña",
  "Paraguayo": "Melocotón y piña",
  "Albaricoque": "Melocotón y piña",
  "Ciruela": "Fruta",
  "Uva": "Fruta",
  "Sandía": "Fruta",
  "Melón": "Fruta",
  "Piña": "Melocotón y piña",
  "Mango": "Fruta",
  "Papaya": "Fruta",
  "Aguacate": "Fruta",
  "Kiwi": "Fruta",
  "Fresa": "Fruta",
  "Frambuesa": "Fruta",
  "Arándano": "Fruta",
  "Mora": "Fruta",
  "Grosella": "Fruta",
  "Granada": "Fruta",
  "Higo": "Fruta",
  "Caqui": "Fruta",
  "Chirimoya": "Fruta",
  "Lichi": "Fruta",
  "Maracuyá": "Fruta",
  "Coco": "Fruta",
  "Limón": "Fruta",
  "Lima": "Fruta",
  "Pomelo": "Fruta",
  "Mandarina": "Fruta",
  "Naranja": "Naranja",
  "Clementina": "Fruta",
  "Níspero": "Fruta",

  // Frutos secos y fruta desecada
  "Almendras": "Frutos secos y fruta desecada",
  "Nueces": "Frutos secos y fruta desecada",
  "Avellanas": "Frutos secos y fruta desecada",
  "Pistachos": "Frutos secos y fruta desecada",
  "Anacardos": "Frutos secos y fruta desecada",
  "Piñones": "Frutos secos y fruta desecada",
  "Cacahuetes": "Frutos secos y fruta desecada",
  "Castañas": "Frutos secos y fruta desecada",
  "Pasas": "Frutos secos y fruta desecada",
  "Ciruelas pasas": "Frutos secos y fruta desecada",
  "Higos secos": "Frutos secos y fruta desecada",
  "Dátiles": "Frutos secos y fruta desecada",
  "Orejones": "Frutos secos y fruta desecada",
  "Arándanos secos": "Frutos secos y fruta desecada",
  "Coco rallado": "Frutos secos y fruta desecada",
  "Fruta deshidratada": "Frutos secos y fruta desecada",
  "Mix de frutos secos": "Frutos secos y fruta desecada",

  // Arroz
  "Arroz":"Arroz",
  "Arroz blanco": "Arroz",
  "Arroz integral": "Arroz",
  "Arroz bomba": "Arroz",
  "Arroz basmati": "Arroz",
  "Arroz jazmín": "Arroz",
  "Arroz salvaje": "Arroz",
  "Arroz vaporizado": "Arroz",
  "Arroz para paella": "Arroz",
  "Arroz para risotto": "Arroz",
  "Arroz redondo": "Arroz",
  "Arroz largo": "Arroz",
  "Arroz thai": "Arroz",

  // Legumbres
  "Garbanzos": "Legumbres",
  "Lentejas": "Legumbres",
  "Alubias blancas": "Legumbres",
  "Alubias pintas": "Legumbres",
  "Alubias negras": "Legumbres",
  "Alubias rojas": "Legumbres",
  "Judías blancas": "Legumbres",
  "Judías pintas": "Legumbres",
  "Guisantes secos": "Legumbres",
  "Habas secas": "Legumbres",
  "Soja": "Legumbres",
  "Lenteja pardina": "Legumbres",
  "Lenteja beluga": "Legumbres",
  "Garbanzo pedrosillano": "Legumbres",
  "Garbanzo lechoso": "Legumbres",

  // Pasta y fideos
  "Pasta": "Pasta y fideos",
  "Macarrones": "Pasta y fideos",
  "Espaguetis": "Pasta y fideos",
  "Tallarines": "Pasta y fideos",
  "Fusilli": "Pasta y fideos",
  "Penne": "Pasta y fideos",
  "Lasaña": "Pasta y fideos",
  "Canelones": "Pasta y fideos",
  "Fideos": "Pasta y fideos",
  "Fideos chinos": "Pasta y fideos",
  "Fideos de arroz": "Pasta y fideos",
  "Fideos de huevo": "Pasta y fideos",
  "Fideos udon": "Pasta y fideos",
  "Fideos soba": "Pasta y fideos",
  "Pasta integral": "Pasta y fideos",
  "Pasta de colores": "Pasta y fideos",
  "Pasta sin gluten": "Pasta y fideos",
  "Cuscús": "Pasta y fideos",
  "Bulgur": "Pasta y fideos",
  "Quinoa": "Pasta y fideos",

  // Pan de horno
  "Pan":"Pan de horno",
  "Pan de barra": "Pan de horno",
  "Pan rústico": "Pan de horno",
  "Pan de pueblo": "Pan de horno",
  "Pan integral": "Pan de horno",
  "Pan de centeno": "Pan de horno",
  "Pan de espelta": "Pan de horno",
  "Pan de semillas": "Pan de horno",
  "Pan de molde integral": "Pan de molde y otras especialidades",
  "Pan de molde blanco": "Pan de molde y otras especialidades",
  "Pan de molde sin corteza": "Pan de molde y otras especialidades",
  "Pan de molde multicereales": "Pan de molde y otras especialidades",
  "Pan de molde sin gluten": "Pan de molde y otras especialidades",
  "Pan de hamburguesa": "Pan de molde y otras especialidades",
  "Pan de perrito": "Pan de molde y otras especialidades",
  "Pan de pita": "Pan de molde y otras especialidades",
  "Pan de chapata": "Pan de molde y otras especialidades",
  "Pan de ajo": "Pan de molde y otras especialidades",
  "Pan de pasas": "Pan de molde y otras especialidades",
  "Pan de nueces": "Pan de molde y otras especialidades",
  "Pan de maíz": "Pan de molde y otras especialidades",
  "Pan de molde tostado": "Pan de molde y otras especialidades",
  "Panecillos": "Pan de molde y otras especialidades",
  "Baguette": "Pan de horno",
  "Bollos preñados": "Pan de molde y otras especialidades",

  // Harina y preparado repostería
  "Harina": "Harina y preparado repostería",
  "Harina de trigo": "Harina y preparado repostería",
  "Harina integral": "Harina y preparado repostería",
  "Harina de fuerza": "Harina y preparado repostería",
  "Harina de repostería": "Harina y preparado repostería",
  "Harina de maíz": "Harina y preparado repostería",
  "Harina de centeno": "Harina y preparado repostería",
  "Harina de espelta": "Harina y preparado repostería",
  "Harina de avena": "Harina y preparado repostería",
  "Harina de garbanzo": "Harina y preparado repostería",
  "Harina sin gluten": "Harina y preparado repostería",
  "Pan rallado": "Pan tostado y rallado",
  "Levadura en polvo": "Harina y preparado repostería",
  "Levadura fresca": "Harina y preparado repostería",
  "Levadura seca": "Harina y preparado repostería",
  "Gasificante": "Harina y preparado repostería",
  "Polvos de hornear": "Harina y preparado repostería",
  "Masa de hojaldre": "Harina y preparado repostería",
  "Masa de pizza": "Harina y preparado repostería",
  "Masa de empanada": "Harina y preparado repostería",
  "Masa de pan": "Harina y preparado repostería",
  "Masa de crepes": "Harina y preparado repostería",
  "Masa de buñuelos": "Harina y preparado repostería",
  "Masa de churros": "Harina y preparado repostería",
  "Masa de croissant": "Harina y preparado repostería",
  "Masa de brioche": "Harina y preparado repostería",
  "Masa de magdalenas": "Harina y preparado repostería",
  "Masa de bizcocho": "Harina y preparado repostería",
  "Masa de tarta": "Harina y preparado repostería",
  "Masa de galletas": "Harina y preparado repostería",
  "Masa de rosquillas": "Harina y preparado repostería",
  "Masa de empanadillas": "Harina y preparado repostería",
  "Masa de canelones": "Harina y preparado repostería",
  "Masa de lasaña": "Harina y preparado repostería",
  "Masa de raviolis": "Harina y preparado repostería",
  "Masa de tortellini": "Harina y preparado repostería",
  "Masa de gnocchi": "Harina y preparado repostería",
  "Masa de fideos": "Harina y preparado repostería",
  "Masa de tallarines": "Harina y preparado repostería",
  "Masa de espaguetis": "Harina y preparado repostería",
  "Masa de macarrones": "Harina y preparado repostería",
  "Masa de fusilli": "Harina y preparado repostería",
  "Masa de penne": "Harina y preparado repostería",
  "Masa de farfalle": "Harina y preparado repostería",
  "Masa de conchiglie": "Harina y preparado repostería",
  "Masa de rotini": "Harina y preparado repostería",
  "Masa de orzo": "Harina y preparado repostería",
  "Masa de couscous": "Harina y preparado repostería",
  "Masa de quinoa": "Harina y preparado repostería",
  "Masa de bulgur": "Harina y preparado repostería",
  "Masa de arroz": "Harina y preparado repostería",
  "Masa de maíz": "Harina y preparado repostería",
  "Masa de trigo sarraceno": "Harina y preparado repostería",
  "Masa de mijo": "Harina y preparado repostería",
  "Masa de amaranto": "Harina y preparado repostería",
  "Masa de teff": "Harina y preparado repostería",
  "Masa de sorgo": "Harina y preparado repostería",
  "Masa de kamut": "Harina y preparado repostería",
  "Masa de espelta": "Harina y preparado repostería",
  "Masa de trigo duro": "Harina y preparado repostería",
  "Masa de trigo blando": "Harina y preparado repostería",
  "Masa de trigo integral": "Harina y preparado repostería",

  //Caldos
"Caldo de ave": ["Sopa y caldo"],
"Caldo de pollo": ["Sopa y caldo"],
"Caldo de cocido": ["Sopa y caldo"],
"Caldo de carne": ["Sopa y caldo"],
"Caldo de pescado": ["Sopa y caldo"],
"Caldo de verduras": ["Sopa y caldo"],
"Caldo para paella": ["Sopa y caldo"],
"Caldo para fideuá": ["Sopa y caldo"],
"Caldo de marisco": ["Sopa y caldo"],
"Caldo casero": ["Sopa y caldo"],
"Caldo 100% natural": ["Sopa y caldo"]

}